// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import GymMapController from "./gym_map_controller"
application.register("gym-map", GymMapController)

import GymMapDisplayController from "./gym_map_display_controller"
application.register("gym-map-display", GymMapDisplayController)

import WorkoutToggleController from "./workout_toggle_controller"
application.register("workout-toggle", WorkoutToggleController)
